name: sampleproject
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  camera: ^0.10.0+4
  flutter:
    sdk: flutter
  google_mlkit_text_recognition: ^0.14.0
  permission_handler: ^11.3.1
  image_cropper: ^8.1.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  dotted_border: ^2.1.0
  gemini_ai: ^1.0.1
  flython: ^0.2.0
  http: ^1.3.0
  flutter_dotenv: ^5.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true
